version: 2
jobs:
  build:
    macos:
      xcode: "10.2.1"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: xcodebuild -project Cirlcle_CI_Demo.xcodeproj

workflows:
  version: 2
  build:
    jobs:
      build