version: 2
jobs:
  build-and-test:
    macos:
      xcode: "10.2.1"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: xcodebuild -project Circle_CI_Demo.xcodeproj -scheme "Circle_CI_Demo" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=11.3,name=iPhone X" -enableCodeCoverage YES test

workflows:
  version: 2
  primary:
    jobs:
      build-and-test