version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.3.0"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: xcodebuild -project Cheers.xcodeproj -scheme "Cheers-iOS" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=11.3,name=iPhone X" -enableCodeCoverage YES test

workflows:
  version: 2
  primary:
    jobs:
      build-and-test